available_props: ["api", "model", "image_api", "chat_mode", "lang"]

info:
  api:
    name:
      es: APIs ğŸ”Œ
      ar: ÙˆØ§Ø¬Ù‡Ø§Øª Ø¨Ø±Ù…Ø¬Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚Ø§Øª ğŸ”Œ
      en: APIs ğŸ”Œ
      jp: API ğŸ”Œ
      zh: API ğŸ”Œ
      de: APIs ğŸ”Œ
      fr: APIs ğŸ”Œ
      ru: API ğŸ”Œ
      pt: APIs ğŸ”Œ
      it: API ğŸ”Œ
      nl: API's ğŸ”Œ
  model:
    name:
      es: Modelos ğŸ§ 
      ar: Ù†Ù…Ø§Ø°Ø¬ ğŸ§ 
      en: Models ğŸ§ 
      jp: ãƒ¢ãƒ‡ãƒ« ğŸ§ 
      zh: æ¨¡å‹ ğŸ§ 
      de: Modelle ğŸ§ 
      fr: ModÃ¨les ğŸ§ 
      ru: ĞœĞ¾Ğ´ĞµĞ»Ğ¸ ğŸ§ 
      pt: Modelos ğŸ§ 
      it: Modelli ğŸ§ 
      nl: Modellen ğŸ§ 
  image_api:
    name:
      es: ImÃ¡genes ğŸ–¼ï¸
      ar: ØµÙˆØ± ğŸ–¼ï¸
      en: Images ğŸ–¼ï¸
      jp: ç”»åƒ ğŸ–¼ï¸
      zh: å›¾ç‰‡ ğŸ–¼ï¸
      de: Bilder ğŸ–¼ï¸
      fr: Images ğŸ–¼ï¸
      ru: Ğ˜Ğ·Ğ¾Ğ±Ñ€Ğ°Ğ¶ĞµĞ½Ğ¸Ñ ğŸ–¼ï¸
      pt: Imagens ğŸ–¼ï¸
      it: Immagini ğŸ–¼ï¸
      nl: Afbeeldingen ğŸ–¼ï¸
  chat_mode:
    name:
      es: Modos de chat ğŸ’¬
      ar: Ø£ÙˆØ¶Ø§Ø¹ Ø§Ù„Ø¯Ø±Ø¯Ø´Ø© ğŸ’¬
      en: Chat modes ğŸ’¬
      jp: ãƒãƒ£ãƒƒãƒˆãƒ¢ãƒ¼ãƒ‰ ğŸ’¬
      zh: èŠå¤©æ¨¡å¼ ğŸ’¬
      de: Chat-Modi ğŸ’¬
      fr: Modes de chat ğŸ’¬
      ru: Ğ ĞµĞ¶Ğ¸Ğ¼Ñ‹ Ñ‡Ğ°Ñ‚Ğ° ğŸ’¬
      pt: Modos de chat ğŸ’¬
      it: ModalitÃ  di chat ğŸ’¬
      nl: Chatmodi ğŸ’¬
  lang:
    name:
      es: Idiomas ğŸ‡ªğŸ‡¸
      ar: Ø§Ù„Ù„ØºØ§Øª ğŸ‡¦ğŸ‡ª
      en: Languages ğŸ‡¬ğŸ‡§
      jp: è¨€èª ğŸ‡¯ğŸ‡µ
      zh: è¯­è¨€ ğŸ‡¨ğŸ‡³
      de: Sprachen ğŸ‡©ğŸ‡ª
      fr: Langues ğŸ‡«ğŸ‡·
      ru: Ğ¯Ğ·Ñ‹ĞºĞ¸ ğŸ‡·ğŸ‡º
      pt: Idiomas ğŸ‡µğŸ‡¹
      it: Lingue ğŸ‡®ğŸ‡¹
      nl: Talen ğŸ‡³ğŸ‡±

imaginepy:
  available_options: ["imaginepy_styles", "imaginepy_ratios"]
